services:
  authlextaticoapi:
    image: ${DOCKER_REGISTRY-}authlextaticoapi
    container_name: auth_lextatico_api_prd
    build:
      context: .
      dockerfile: src/Auth.Lextatico.Api/Dockerfile
    networks:
      - Lextatico
    ports:
      - 9000:9000
      - 9001:9001
