services:
  authlextaticoapi:
    image: ${DOCKER_REGISTRY-}authlextaticoapi
    container_name: auth_lextatico_api
    build:
      context: .
      dockerfile: src/Auth.Lextatico.Api/Dockerfile-debug
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - Lextatico
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw