services:
  authlextaticoapi:
    image: ${DOCKER_REGISTRY-}authlextaticoapi
    container_name: auth_lextatico_api
    build:
      context: .
      dockerfile: src/Auth.Lextatico.Api/Dockerfile
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - Lextatico
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    depends_on:
      - authlextaticoapi
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - Lextatico
    cap_drop:
      - NET_RAW
